# Markov Reward Process (MRP) Explanation

## Introduction
A **Markov Reward Process (MRP)** is a mathematical framework used to model sequential decision-making problems where transitions between states occur probabilistically, and each state provides a numerical reward. It is a simplified version of a **Markov Decision Process (MDP)** that does not involve actions.

An MRP is formally defined as a tuple **(S, P, R, γ)**:
- **S**: A finite set of states.
- **P**: A state transition probability matrix where \( P(s' | s) \) represents the probability of transitioning from state \( s \) to state \( s' \).
- **R**: A reward function mapping each state to a real-valued reward \( R(s) \).
- **$\gamma$**: A discount factor $$ \gamma \in [0,1] $$ that determines the importance of future rewards.
---

## MRP Bellman Equation

$$
V(s) = R(s) + \gamma \sum_{s' \in S} P(s' \mid s) V(s')
$$

where:
- \(V(s)\) is the expected **long-term reward** when starting from state \(s\).
- \(R(s)\) is the **immediate reward** received in state \(s\).
- \(\gamma\) is the **discount factor**, where \(0 \leq \gamma \leq 1\), which determines the importance of future rewards.
- \(P(s' \mid s)\) is the **transition probability**, representing the probability of moving from state \(s\) to \(s'\).

### Matrix Representation

For a finite set of states $(S = \{s_1, s_2, \dots, s_n\})$, we can represent the Bellman equation in **matrix form**:

$$
V = (I - \gamma P)^{-1} R
$$

where:
- \(V\) is the column vector of state values: \(V = [V(s_1), V(s_2), \dots, V(s_n)]^T\).
- \(R\) is the column vector of rewards: \(R = [R(s_1), R(s_2), \dots, R(s_n)]^T\).
- \(P\) is the **state transition matrix**, where each entry \(P_{ij} = P(s_j \mid s_i)\).
- \(I\) is the identity matrix.



## Code Explanation

The provided Python code implements an MRP and computes the **state value function \( V(s) \)** using the Bellman equation.

### **1. Defining the MRP Components**
```python
states = ['A', 'B', 'C', 'D']


In [4]:
import numpy as np

states = ['A', 'B', 'C', 'D']

transition_matrix = np.array([
    [0.0, 0.5, 0.5, 0.0],  # A -> {B: 0.5, C: 0.5}
    [0.0, 0.0, 0.7, 0.3],  # B -> {C: 0.7, D: 0.3}
    [0.0, 0.0, 0.0, 1.0],  # C -> {D: 1.0}
    [0.0, 0.0, 0.0, 1.0]   # D -> {D: 1.0} (terminal state)
])

# R(s)
rewards = np.array([1, 0, -1, 2])  # A: +1, B: 0, C: -1, D: +2

# discount rate
gamma = 0.9

# bellman equation
I = np.eye(len(states))
V = np.linalg.inv(I - gamma * transition_matrix) @ rewards

for state, value in zip(states, V):
    print(f"V({state}) = {value:.2f}")

V(A) = 15.90
V(B) = 16.11
V(C) = 17.00
V(D) = 20.00


# **Markov Decision Process (MDP) Explanation**

## **Introduction**
A **Markov Decision Process (MDP)** is a mathematical framework used in reinforcement learning to model decision-making in environments where outcomes are partly random and partly under the control of an agent.

An MDP is formally defined as a tuple **(S, A, P, R, γ)**:
- **S**: A finite set of states.
- **A**: A finite set of actions available to the agent.
- **P(s' | s, a)**: A transition probability matrix that represents the probability of transitioning from state \( s \) to \( s' \) given action \( a \).
- **R(s, a)**: A reward function that maps each state-action pair to a numerical reward.
- **$\gamma$**: A discount factor $( \gamma \in [0,1] )$ that determines the importance of future rewards.

The goal of an MDP is to find an **optimal policy** $( \pi^*(s) )$ that maximizes the **expected cumulative reward** over time.

---

## Bellman Optimality Equation for MDP

In a Markov Decision Process (MDP) without a given policy, we are interested in finding the **optimal state value function** \(V^*(s)\). This function represents the maximum expected cumulative reward achievable from state \(s\) by choosing the best possible actions. The Bellman Optimality Equation is given by:

$$
V^*(s) = \max_{a \in A} \left[ R(s, a) + \gamma \sum_{s' \in S} P(s' \mid s, a) V^*(s') \right]
$$

where:
- $(V^*(s))$ is the optimal expected **long-term reward** from state \(s\).
- $(R(s, a))$ is the **immediate reward** received after taking action \(a\) in state \(s\).
- $(\gamma)$ is the **discount factor**, with \(0 \leq \gamma \leq 1\), which scales the importance of future rewards.
- $(P(s' \mid s, a))$ is the **transition probability**, representing the probability of moving to state \(s'\) from state \(s\) after taking action \(a\).
- $(A)$ is the set of all available actions.



## **Code Explanation**
The provided Python code implements an MDP and solves it using the **Value Iteration algorithm**, which finds the optimal **state value function** \( V^*(s) \) and the corresponding **optimal policy** $( \pi^*(s) )$.

### **1. Defining the MDP Components**
```python
states = ["A", "B", "C", "D"]
actions = ["left", "right"]


In [6]:

states = ["A", "B", "C", "D"]
actions = ["left", "right"]

# P(s' | s, a)
transition_probs = {
    "A": {"left": {"A": 1.0}, "right": {"B": 1.0}},
    "B": {"left": {"A": 0.5, "B": 0.5}, "right": {"C": 1.0}},
    "C": {"left": {"B": 1.0}, "right": {"D": 1.0}},
    "D": {"left": {"C": 1.0}, "right": {"D": 1.0}},  # 종료 상태
}

# R(s, a)
rewards = {
    "A": {"left": 0, "right": 1},
    "B": {"left": -1, "right": 2},
    "C": {"left": -2, "right": 3},
    "D": {"left": 0, "right": 0},
}

# (Gamma)
gamma = 0.9

# Ininital Value of State
V = {s: 0 for s in states}

# **Value Iteration Algorithm**
tolerance = 1e-6 
while True:
    delta = 0
    new_V = V.copy()
    
    for s in states:
        if s == "D":  # 종료 상태는 그대로 유지
            continue

        # 가능한 모든 행동에 대해 기대 가치 계산
        action_values = []
        for a in actions:
            value = sum(p * (rewards[s][a] + gamma * V[s_next])
                        for s_next, p in transition_probs[s][a].items())
            action_values.append(value)

        # 새로운 가치 함수 업데이트
        new_V[s] = max(action_values)
        delta = max(delta, abs(new_V[s] - V[s]))

    V = new_V  # 가치 함수 업데이트

    if delta < tolerance:  # 수렴 조건
        break

# 최적 정책 추출
policy = {}
for s in states:
    if s == "D":  # 종료 상태는 정책이 필요 없음
        policy[s] = None
        continue
    
    best_action = None
    best_value = float("-inf")
    
    for a in actions:
        value = sum(p * (rewards[s][a] + gamma * V[s_next])
                    for s_next, p in transition_probs[s][a].items())
        if value > best_value:
            best_value = value
            best_action = a
    
    policy[s] = best_action

# 결과 출력
print("Optimal Value Function (V):")
for state in V:
    print(f"V({state}) = {V[state]:.2f}")

print("\nOptimal Policy:")
for state in policy:
    print(f"π({state}) = {policy[state]}")


Optimal Value Function (V):
V(A) = 5.23
V(B) = 4.70
V(C) = 3.00
V(D) = 0.00

Optimal Policy:
π(A) = right
π(B) = right
π(C) = right
π(D) = None


# Markov Decision Process + Policy

## **Introduction**
A **Markov Decision Process (MDP)** is a mathematical framework used in reinforcement learning to model decision-making in environments where outcomes are partly random and partly under the control of an agent.

An MDP is formally defined as a tuple **(S, A, P, R, γ)**:
- **S**: A finite set of states.
- **A**: A finite set of actions available to the agent.
- **P(s' | s, a)**: A transition probability matrix that represents the probability of transitioning from state \( s \) to \( s' \) given action \( a \).
- **R(s, a)**: A reward function that maps each state-action pair to a numerical reward.
- **\(\gamma\)**: A discount factor \( (\gamma \in [0,1]) \) that determines the importance of future rewards.

The goal of an MDP is to find an **optimal policy** \( \pi^*(s) \) that maximizes the **expected cumulative reward** over time.

---

## Bellman Equation for MDP with a Given Policy

When a policy $( \pi )$ is provided, the **state value function** $( V^\pi(s) )$ gives the expected cumulative reward when starting from state ( s ) and following the policy $( \pi )$. The Bellman Equation for a given policy is defined as:

$$
V^\pi(s) = \sum_{a \in A} \pi(a \mid s) \left[ R(s, a) + \gamma \sum_{s' \in S} P(s' \mid s, a) V^\pi(s') \right]
$$

where:
- $( V^\pi(s) )$ is the expected **long-term reward** from state \( s \) when following policy \( \pi \).
- $( \pi(a \mid s) )$ is the probability of taking action \( a \) in state \( s \) under policy \( \pi \).
- $( R(s, a) )$ is the **immediate reward** received after taking action \( a \) in state \( s \).
- $( \gamma )$ is the **discount factor**, with \( 0 \leq \gamma \leq 1 \), which scales the importance of future rewards.
- $( P(s' \mid s, a) )$ is the **transition probability**, representing the probability of moving to state \( s' \) from state \( s \) after taking action \( a )$.

---

## **Code Explanation**
The following Python code implements a simple MDP and evaluates a given policy using the **Value Iteration algorithm**. This process computes the state value function \( V^\pi(s) \) and can be extended to derive the corresponding policy \( \pi(s) \).



In [9]:
import numpy as np

# Define states and actions
states = ["A", "B", "C", "D"]
actions = ["left", "right"]

# Transition probabilities P(s' | s, a) for the MDP
transition_probs = {
    "A": {"left": {"A": 1.0}, "right": {"B": 1.0}},
    "B": {"left": {"A": 0.5, "B": 0.5}, "right": {"C": 1.0}},
    "C": {"left": {"B": 1.0}, "right": {"D": 1.0}},
    "D": {"left": {"C": 1.0}, "right": {"D": 1.0}},  # terminal state
}

# Reward function R(s, a)
rewards = {
    "A": {"left": 0, "right": 1},
    "B": {"left": -1, "right": 2},
    "C": {"left": -2, "right": 3},
    "D": {"left": 0, "right": 0},  # terminal state
}

# Discount factor (gamma)
gamma = 0.9

# Define a policy π(s) (e.g., always choose 'right')
policy = {
    "A": "right",
    "B": "right",
    "C": "right",
    "D": None  # No action for the terminal state
}

# Convert the MDP to an MRP: Compute new P^π and R^π
P_pi = np.zeros((len(states), len(states)))
R_pi = np.zeros(len(states))

state_idx = {s: i for i, s in enumerate(states)}  # Map state names to indices

for s in states:
    if s == "D":  # Terminal state remains unchanged
        P_pi[state_idx[s], state_idx[s]] = 1.0
        R_pi[state_idx[s]] = 0
        continue

    a = policy[s]  # Selected action
    for s_next, prob in transition_probs[s][a].items():
        P_pi[state_idx[s], state_idx[s_next]] = prob

    R_pi[state_idx[s]] = rewards[s][a]

# Solve the MRP Bellman equation: V^π = (I - γP^π)^(-1) R^π
I = np.eye(len(states))
V_pi = np.linalg.inv(I - gamma * P_pi) @ R_pi

# Print the results
print("MRP Transition Matrix (P^π):")
print(P_pi)

print("\nMRP Reward Vector (R^π):")
print(R_pi)

print("\nState Value Function under the Policy (V^π):")
for s, v in zip(states, V_pi):
    print(f"V^π({s}) = {v:.2f}")


MRP Transition Matrix (P^π):
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]

MRP Reward Vector (R^π):
[1. 2. 3. 0.]

State Value Function under the Policy (V^π):
V^π(A) = 5.23
V^π(B) = 4.70
V^π(C) = 3.00
V^π(D) = 0.00
